name: main

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: '${{ secrets.COVERALLS_REPO_TOKEN }}'
      COVERALLS_GIT_COMMIT: '${{ github.sha }}'
      COVERALLS_GIT_BRANCH: '${{ github.ref }}'

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Yarn Cache ğŸ’¾
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install Node.js ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Build and Test ğŸ‘·
        run: |
          yarn build:src
          yarn test:unit
        env:
          CI: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
